### ISSUE TITLE
How to refresh the token

### ISSUE THREAD

**Issue by ksaye** [coolkit-carl/eWeLinkOAuthLoginDemo#2]
Great sample code that I have already adapted for my need.

I see that the token is set to expire in ~30 days.  Using your sample code, how would you refresh the token?

Also, I see that the AppID (https://dev.ewelink.cc/#/console) expires in 1 year, how can we capture the expiration or extend the expiration.

**Comment by coolkit-carl** [comment]
https://github.com/coolkit-carl/ewelink-api-next/blob/main/docs/en/UserManagement.md

```
import eWeLink from 'ewelink-api-next'
const client = new eWeLink.WebAPI({
  ...
})


client.user.refreshToken({
  rt: 'This is the refreshToken you obtained earlier'
})
```

**Comment by ksaye** [comment]
@coolkit-carl, I am getting the error "authorization" with value "Bearer" fails"

Here is the code:

          import { client } from './config.js'      

          const login = async () => {
          if (!fs.existsSync('./token.json')) {
              throw new Error('token.json not found, please goto {ipaddress}:' + port + "/login")
          }
      
          // get token
          const LoggedInfo = JSON.parse(fs.readFileSync('./token.json', 'utf-8'))
          console.info(LoggedInfo)
      
          var dateCompare = new Date();
          dateCompare.setDate(dateCompare.getDate() - 7);
          var expireDate = new Date(0); 
          expireDate.setUTCSeconds(LoggedInfo.data.atExpiredTime);
          //if (expireDate >= dateCompare) {
              const refresh = await client.user.refreshToken({
                  rt: LoggedInfo.data.refreshToken
              });
      
              console.log(refresh);

Here is the first console.log (removed characters for sensitivity reasons:

      {
        status: 200,
        responseTime: 1318,
        error: 0,
        msg: '',
        data: {
          accessToken: 'dba5efb*******************ab5323bc3aba2',
          atExpiredTime: 1695225134770,
          refreshToken: '3abbbf88****************4260989f2',
          rtExpiredTime: 1697817134790
        },
        region: 'us'
      }

And here is the error on the second console.log:

      {
        status: 200,
        responseTime: null,
        error: 400,
        msg: '"authorization" with value "Bearer" fails to match the required pattern: /^Bearer\\s[0-9a-f]+$/',
        data: {}
      }

**Comment by coolkit-carl** [comment]
Ensure that your dependency ewelink-api-text version is greater than or equal to 1.0.1. I have fixed an issue with the refreshToken method.

Also, you can check the content of your request log.

**Comment by coolkit-carl** [comment]
Ensure that your dependency ewelink-api-text version is greater than or equal to 1.0.1. I have fixed an issue with the refreshToken method.

Also, you can check the content of your request log.

**Comment by ksaye** [comment]
How can I check the content of my request log?

With version 1.0.1, I am getting a different error, shown below.  I have confirmed that the token works, but it will not refresh.

        npm view ewelink-api-next version
        1.0.1



sample code:

          import { client } from './config.js'
          import * as fs from 'fs'
          
          var LoggedInfo = JSON.parse(fs.readFileSync('./token.json', 'utf-8'))
          console.info(LoggedInfo)
          console.log('Token expired, refreshing token')
          console.log('token is: ' + LoggedInfo.data.refreshToken)
          
          client.at = LoggedInfo.data?.accessToken
          client.region = LoggedInfo?.region || 'us'
          client.setUrl(LoggedInfo?.region || 'us')
          
          const refreshStatus = await client.user.refreshToken({
            rt: LoggedInfo.data.refreshToken,
          })
          console.log('Finished refreshing token')
          console.log(refreshStatus)

response:

        {
          status: 200,
          responseTime: 1318,
          error: 0,
          msg: '',
          data: {
            accessToken: 'dba5efb1***************323bc3aba2',
            atExpiredTime: 1695225134770,
            refreshToken: '3abbbf8***************44260989f2',
            rtExpiredTime: 1697817134790
          },
          region: 'us'
        }
        Token expired, refreshing token
        token is: 3abbbf8***************44260989f2
        Finished refreshing token
        {
          status: 200,
          responseTime: 374,
          error: 405,
          msg: "can't find the account with this rt!",
          data: {}
        }

**Comment by ksaye** [comment]
Nevermind.

I tried my origional code and got the error:

      {
        status: 200,
        responseTime: 339,
        error: 401,
        msg: 'cannot found access token info',
        data: {}
      }
      
I then re created token.json and it now works.

**Comment by coolkit-carl** [comment]
> Nevermind.
> 
> I tried my origional code and got the error:
> 
> ```
>   {
>     status: 200,
>     responseTime: 339,
>     error: 401,
>     msg: 'cannot found access token info',
>     data: {}
>   }
> ```
> 
> I then re created token.json and it now works.

There may be an error here:

client.region = LoggedInfo?.region || 'us'
client.setUrl(LoggedInfo?.region || 'us')

When I wrote before, I brought back the region of the jump page and placed it in LoggedInfo.region. You may not have filled it out.
<img width="478" alt="image" src="https://github.com/coolkit-carl/eWeLinkOAuthLoginDemo/assets/50738270/ca6e01c5-026b-40f4-9202-da24f0e5ad41">

**Comment by coolkit-carl** [comment]
1. Ensure that the APPID you are using is created by yourself. 
2. Any duplicate login between the same APPID and the same account will invalidate the previous token

**Comment by pazzagsi2** [comment]
HI,

Is it possible to refresh a token before it expires?

I don't understand otherwise why with the following code I don't get a new token but the 400 error



```
import { client } from './config.js'
import * as fs from 'fs'

const controlDeviceDemo = async () => {
  // If the file does not exist, directly report an error
  if (!fs.existsSync('./token.json')) {
    throw new Error('token.json not found, please run login.js first')
  }

  // get token
  let LoggedInfo = JSON.parse(fs.readFileSync('./token.json', 'utf-8'))
   console.info(LoggedInfo)
  client.at = LoggedInfo.data?.accessToken
  client.region = LoggedInfo?.region || 'eu'
  client.setUrl(LoggedInfo?.region || 'eu')
  // Check if the token has expired, and refresh the token if it has expired
  if (
   true    // force new token
  ) {
  
  
    console.log('Token expired, refreshing token')
    const refreshStatus = await client.user.refreshToken({
      rt: LoggedInfo.data?.refreshToken
    })
    console.log(refreshStatus)
//    console.log("______",LoggedInfo.data?.refreshToken)
    if (refreshStatus.error === 0) {
      // You can also use built-in storage
      // client.storage.set('token', {...})
      fs.writeFileSync(
        './token.json',
        JSON.stringify({
          status: 200,
          responseTime: 0,
          error: 0,
          msg: '',
          data: {
            accessToken: refreshStatus?.data?.at,
            atExpiredTime: Date.now() + 2592000000,
            refreshToken: refreshStatus?.data?.rt,
            rtExpiredTime: Date.now() + 5184000000,
          },
          region: client.region,
        })
      )
      LoggedInfo = JSON.parse(fs.readFileSync('./token.json', 'utf-8'))
    }
  }

  if (LoggedInfo.data?.rtExpiredTime < Date.now()) {
    console.log('Failed to refresh token, need to log in again to obtain token')
    return
  }

  // Get device list
  try {
    let thingList = await client.device.getAllThingsAllPages({}) // { status: 200, error: 0, msg: "", data: { thingList: [{ itemType: 1, itemData: {...} }], total: 1 } };
    console.log(JSON.stringify(thingList, null, 2))
    if (thingList?.error === 0) {
      thingList = thingList.data.thingList
      console.log(thingList)
      // Control the first single channel device, just an example
      if (thingList[0]?.itemData.extra.uiid === 1) {
        await client.device.setThingStatus({
          type: 1,
          id: thingList[0].itemData.deviceid,
          params: {
            switch: 'on', // Specific control instructions: https://coolkit-technologies.github.io/eWeLink-API/#/en/UIIDProtocol
          },
        })
      }
      // Control the first dual channel device, just an example
      if (thingList[0]?.itemData.extra.uiid === 4) {
        await client.device.setThingStatus({
          type: 1,
          id: thingList[0].itemData.deviceid,
          params: {
            switches: [
              { switch: 'off', outlet: 0 },
              { switch: 'off', outlet: 1 },
              { switch: 'off', outlet: 2 },
              { switch: 'off', outlet: 3 },
            ],
          },
        })
      }
    }
  } catch (e) {
    console.log(e)
  }
}

controlDeviceDemo()

console.log("---------");
```

response 

```

_________
{
  status: 200,
  responseTime: 579,
  error: 0,
  msg: '',
  data: {
    accessToken: 'f5****e9',
    atExpiredTime: 1696052240806,  //  ~  2023-09-30__07:37:806
    refreshToken: 'c4****92',
    rtExpiredTime: 1698644240845  //  ~ 2023-10-30__06:37:845
  },
  region: 'eu'
}
Token expired, refreshing token
---------
{
  status: 200,
  responseTime: 506,
  error: 400,
  msg: '"authorization" with value "Sign [object Object]" fails to match the required pattern: /^(Sign\\s[0-9a-zA-Z+/]+={0,2}|Bearer\\s[0-9a-f]+)$/',
  data: {}
}
{
  "status": 200,
  "error": 0,
  "msg": "",
  "data": {
    "thingList": [],
    "total": 0
  }
}
[]
Done.
```
