### ISSUE TITLE
Cant login using https://c2ccdn.coolkit.cc/oauth/index.html

### ISSUE THREAD

**Issue by Kiogora** [coolkit-carl/eWeLinkOAuthLoginDemo#5]
Hi,

I have an authenticated account with valid app_id. Free tier. I have run this code, however, I cant login via the authorization page generated https://c2ccdn.coolkit.cc/oauth/index.html by this repository. Kindly assist.  A peek at the browser console shows:

incorrect redirectUrl:undefined

Also is the sonoff POW Elite part of the brands that do not need paid authorization from other manufacturer.

Regards,
Alois.

**Comment by Kiogora** [comment]
Tried to login via the same and viewed the javascript console. It says:

Access to fetch at 'https://apia.coolkit.cn/v2/user/oauth/code' from origin 'https://c2ccdn.coolkit.cc' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

**Comment by Kiogora** [comment]
![image](https://github.com/coolkit-carl/eWeLinkOAuthLoginDemo/assets/23386986/6612cd52-059e-4d80-8794-f2d9474b89c0)

These are my details on the said page

**Comment by Kiogora** [comment]
I have checked my dev.ewelink.cc acount and it says: 获取信息有误，请刷新页面重新获取！

I have to fill in my application information again. I am not sure what is happening.

**Comment by Kiogora** [comment]
I see that it is back! I have the APP ID and APP Secret. However the issue still persists. After using npm run start and logging in, the interface says:

email must be a valid email

I don't know why this new API seems so difficult to use

**Comment by Kiogora** [comment]
![image](https://github.com/coolkit-carl/eWeLinkOAuthLoginDemo/assets/23386986/42517c88-c5fe-4b44-8b8b-d8099f60662b)

**Comment by Kiogora** [comment]
Resolved, the redirect url was not being set well in eWeLinkOAuthLoginDemo/node_modules/ewelink-api-next/dist/ as set_url was setting to undefined, despite being defined as 'eu'. I am still digging into this, but setting eu in this.setUrl() in the same file worked. I am still digging around to see why this occured.

**Comment by Kiogora** [comment]
I am however leaving the issue open till I find the reason.

**Comment by Kiogora** [comment]
In the meantime, a response to:

is the sonoff POW Elite part of the brands that do not need paid authorization from other manufacturer would be highly appreciated.

**Comment by coolkit-carl** [comment]
1. This example requires that redirectUrl be defined as http://127.0.0.1:8000/redirectUrl It can be filled in in the Developer Center ->Application Management ->Editing section, which affects the process of creating authorization page URLs and obtaining tokens after successful login. If you can read the document, you will understand this process and logic.

[OAuth2.0 FlowChart](https://coolkit-technologies.github.io/eWeLink-API/en/img/01-OAuth2.0_FlowChart.png)

2. [POWR316D、POWR320D](https://sonoff.tech/product/diy-smart-switches/pow-elite/) belongs to the SONOFF brand model and has been authorized for free.
